var e = require("../../common/vendor.js"),
  c = {
    mixins: [e.AppUtils],
    data: function data() {
      return {
        gradeVisibled: !1,
        grades: ["一年级", "二年级", "三年级", "四年级", "五年级", "六年级"],
        selections: [],
        currentGrade: null,
        currentGender: null,
        sports: [],
        scores: [],
        sportsScore: 0,
        bmiScore: 0,
        totalScore: 0
      };
    },
    watch: {
      currentGrade: function currentGrade(e) {
        e && (this.sportsScore = 0, this.bmiScore = 0, this.totalScore = 0);
      },
      currentGender: function currentGender(e) {
        e && (this.sportsScore = 0, this.bmiScore = 0, this.totalScore = 0);
      }
    },
    methods: {
      onPopupGrade: function onPopupGrade() {
        this.gradeVisibled = !this.gradeVisibled;
      },
      onSelectChange: function onSelectChange(e) {
        this.selections = e.detail.value;
      },
      onCancel: function onCancel() {
        this.gradeVisibled = !1;
      },
      onConfirm: function onConfirm() {
        e.utils.isEmptyArray(this.selections) && (this.selections = [0, 0]), this.currentGrade = this.grades[this.selections[0]], this.currentGender = 0 == this.selections[1] ? "男生" : "女生", this.gradeVisibled = !1, this.getSports(this.currentGrade, this.currentGender);
      },
      onHandleResult: function onHandleResult(e, c) {
        this.sportsScore = 0;
        var r = this.scores.find(function (e) {
          return e.name === c.name;
        });
        r ? this.$set(this.scores, this.scores.indexOf(r), c) : this.scores.push(c);
        for (var i = 0; i < this.scores.length; i++) this.sportsScore += this.scores[i].weightingScore;
        this.totalScore = this.sportsScore + this.bmiScore;
      },
      setBmiScore: function setBmiScore(e) {
        this.bmiScore = e.weightingScore, this.totalScore = this.sportsScore + this.bmiScore;
      },
      getSports: function getSports(e, c) {
        this.sports = [], "一年级" == e && "男生" == c && (this.sports = [{
          name: "肺活量",
          unit: "毫升",
          weighting: .15,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 1700
          }, {
            score: 95,
            achieve: 1600
          }, {
            score: 90,
            achieve: 1500
          }, {
            score: 85,
            achieve: 1400
          }, {
            score: 80,
            achieve: 1300
          }, {
            score: 78,
            achieve: 1240
          }, {
            score: 76,
            achieve: 1180
          }, {
            score: 74,
            achieve: 1120
          }, {
            score: 72,
            achieve: 1060
          }, {
            score: 70,
            achieve: 1e3
          }, {
            score: 68,
            achieve: 940
          }, {
            score: 66,
            achieve: 880
          }, {
            score: 64,
            achieve: 820
          }, {
            score: 62,
            achieve: 760
          }, {
            score: 60,
            achieve: 700
          }, {
            score: 50,
            achieve: 660
          }, {
            score: 40,
            achieve: 620
          }, {
            score: 30,
            achieve: 580
          }, {
            score: 20,
            achieve: 540
          }, {
            score: 10,
            achieve: 500
          }]
        }, {
          name: "50米跑",
          unit: "秒",
          weighting: .2,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 10.2
          }, {
            score: 95,
            achieve: 10.3
          }, {
            score: 90,
            achieve: 10.4
          }, {
            score: 85,
            achieve: 10.5
          }, {
            score: 80,
            achieve: 10.6
          }, {
            score: 78,
            achieve: 10.8
          }, {
            score: 76,
            achieve: 11
          }, {
            score: 74,
            achieve: 11.2
          }, {
            score: 72,
            achieve: 11.4
          }, {
            score: 70,
            achieve: 11.6
          }, {
            score: 68,
            achieve: 11.8
          }, {
            score: 66,
            achieve: 12
          }, {
            score: 64,
            achieve: 12.2
          }, {
            score: 62,
            achieve: 12.4
          }, {
            score: 60,
            achieve: 12.6
          }, {
            score: 50,
            achieve: 12.8
          }, {
            score: 40,
            achieve: 13
          }, {
            score: 30,
            achieve: 13.2
          }, {
            score: 20,
            achieve: 13.4
          }, {
            score: 10,
            achieve: 13.6
          }]
        }, {
          name: "坐位体前屈",
          unit: "厘米",
          weighting: .3,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 16.1
          }, {
            score: 95,
            achieve: 14.6
          }, {
            score: 90,
            achieve: 13
          }, {
            score: 85,
            achieve: 12
          }, {
            score: 80,
            achieve: 11
          }, {
            score: 78,
            achieve: 9.9
          }, {
            score: 76,
            achieve: 8.8
          }, {
            score: 74,
            achieve: 7.7
          }, {
            score: 72,
            achieve: 6.6
          }, {
            score: 70,
            achieve: 5.5
          }, {
            score: 68,
            achieve: 4.4
          }, {
            score: 66,
            achieve: 3.3
          }, {
            score: 64,
            achieve: 2.2
          }, {
            score: 62,
            achieve: 1.1
          }, {
            score: 60,
            achieve: 0
          }, {
            score: 50,
            achieve: -.8
          }, {
            score: 40,
            achieve: -1.6
          }, {
            score: 30,
            achieve: -2.4
          }, {
            score: 20,
            achieve: -3.2
          }, {
            score: 10,
            achieve: -4
          }]
        }, {
          name: "一分钟跳绳",
          unit: "个",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 109
          }, {
            score: 95,
            achieve: 104
          }, {
            score: 90,
            achieve: 99
          }, {
            score: 85,
            achieve: 93
          }, {
            score: 80,
            achieve: 87
          }, {
            score: 78,
            achieve: 80
          }, {
            score: 76,
            achieve: 73
          }, {
            score: 74,
            achieve: 66
          }, {
            score: 72,
            achieve: 59
          }, {
            score: 70,
            achieve: 52
          }, {
            score: 68,
            achieve: 45
          }, {
            score: 66,
            achieve: 38
          }, {
            score: 64,
            achieve: 31
          }, {
            score: 62,
            achieve: 24
          }, {
            score: 60,
            achieve: 17
          }, {
            score: 50,
            achieve: 14
          }, {
            score: 40,
            achieve: 11
          }, {
            score: 30,
            achieve: 8
          }, {
            score: 20,
            achieve: 5
          }, {
            score: 10,
            achieve: 2
          }]
        }]), "一年级" == e && "女生" == c && (this.sports = [{
          name: "肺活量",
          unit: "毫升",
          weighting: .15,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 1400
          }, {
            score: 95,
            achieve: 1300
          }, {
            score: 90,
            achieve: 1200
          }, {
            score: 85,
            achieve: 1100
          }, {
            score: 80,
            achieve: 1e3
          }, {
            score: 78,
            achieve: 960
          }, {
            score: 76,
            achieve: 920
          }, {
            score: 74,
            achieve: 880
          }, {
            score: 72,
            achieve: 840
          }, {
            score: 70,
            achieve: 800
          }, {
            score: 68,
            achieve: 760
          }, {
            score: 66,
            achieve: 720
          }, {
            score: 64,
            achieve: 680
          }, {
            score: 62,
            achieve: 640
          }, {
            score: 60,
            achieve: 600
          }, {
            score: 50,
            achieve: 580
          }, {
            score: 40,
            achieve: 560
          }, {
            score: 30,
            achieve: 540
          }, {
            score: 20,
            achieve: 520
          }, {
            score: 10,
            achieve: 500
          }]
        }, {
          name: "50米跑",
          unit: "秒",
          weighting: .2,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 11
          }, {
            score: 95,
            achieve: 11.1
          }, {
            score: 90,
            achieve: 11.2
          }, {
            score: 85,
            achieve: 11.5
          }, {
            score: 80,
            achieve: 11.8
          }, {
            score: 78,
            achieve: 12
          }, {
            score: 76,
            achieve: 12.2
          }, {
            score: 74,
            achieve: 12.4
          }, {
            score: 72,
            achieve: 12.6
          }, {
            score: 70,
            achieve: 12.8
          }, {
            score: 68,
            achieve: 13
          }, {
            score: 66,
            achieve: 13.2
          }, {
            score: 64,
            achieve: 13.4
          }, {
            score: 62,
            achieve: 13.6
          }, {
            score: 60,
            achieve: 13.8
          }, {
            score: 50,
            achieve: 14
          }, {
            score: 40,
            achieve: 14.2
          }, {
            score: 30,
            achieve: 14.4
          }, {
            score: 20,
            achieve: 14.6
          }, {
            score: 10,
            achieve: 14.8
          }]
        }, {
          name: "坐位体前屈",
          unit: "厘米",
          weighting: .3,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 18.6
          }, {
            score: 95,
            achieve: 17.3
          }, {
            score: 90,
            achieve: 16
          }, {
            score: 85,
            achieve: 14.7
          }, {
            score: 80,
            achieve: 13.4
          }, {
            score: 78,
            achieve: 12.3
          }, {
            score: 76,
            achieve: 11.2
          }, {
            score: 74,
            achieve: 10.1
          }, {
            score: 72,
            achieve: 9
          }, {
            score: 70,
            achieve: 7.9
          }, {
            score: 68,
            achieve: 6.8
          }, {
            score: 66,
            achieve: 5.7
          }, {
            score: 64,
            achieve: 4.6
          }, {
            score: 62,
            achieve: 3.5
          }, {
            score: 60,
            achieve: 2.4
          }, {
            score: 50,
            achieve: 1.6
          }, {
            score: 40,
            achieve: .8
          }, {
            score: 30,
            achieve: 0
          }, {
            score: 20,
            achieve: -.8
          }, {
            score: 10,
            achieve: -1.6
          }]
        }, {
          name: "一分钟跳绳",
          unit: "个",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 117
          }, {
            score: 95,
            achieve: 110
          }, {
            score: 90,
            achieve: 103
          }, {
            score: 85,
            achieve: 95
          }, {
            score: 80,
            achieve: 87
          }, {
            score: 78,
            achieve: 80
          }, {
            score: 76,
            achieve: 73
          }, {
            score: 74,
            achieve: 66
          }, {
            score: 72,
            achieve: 59
          }, {
            score: 70,
            achieve: 52
          }, {
            score: 68,
            achieve: 45
          }, {
            score: 66,
            achieve: 38
          }, {
            score: 64,
            achieve: 31
          }, {
            score: 62,
            achieve: 24
          }, {
            score: 60,
            achieve: 17
          }, {
            score: 50,
            achieve: 14
          }, {
            score: 40,
            achieve: 11
          }, {
            score: 30,
            achieve: 8
          }, {
            score: 20,
            achieve: 5
          }, {
            score: 10,
            achieve: 2
          }]
        }]), "二年级" == e && "男生" == c && (this.sports = [{
          name: "肺活量",
          unit: "毫升",
          weighting: .15,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 2e3
          }, {
            score: 95,
            achieve: 1900
          }, {
            score: 90,
            achieve: 1800
          }, {
            score: 85,
            achieve: 1650
          }, {
            score: 80,
            achieve: 1500
          }, {
            score: 78,
            achieve: 1430
          }, {
            score: 76,
            achieve: 1360
          }, {
            score: 74,
            achieve: 1290
          }, {
            score: 72,
            achieve: 1220
          }, {
            score: 70,
            achieve: 1150
          }, {
            score: 68,
            achieve: 1080
          }, {
            score: 66,
            achieve: 1010
          }, {
            score: 64,
            achieve: 940
          }, {
            score: 62,
            achieve: 870
          }, {
            score: 60,
            achieve: 800
          }, {
            score: 50,
            achieve: 750
          }, {
            score: 40,
            achieve: 700
          }, {
            score: 30,
            achieve: 650
          }, {
            score: 20,
            achieve: 600
          }, {
            score: 10,
            achieve: 550
          }]
        }, {
          name: "50米跑",
          unit: "秒",
          weighting: .2,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 9.6
          }, {
            score: 95,
            achieve: 9.7
          }, {
            score: 90,
            achieve: 9.8
          }, {
            score: 85,
            achieve: 9.9
          }, {
            score: 80,
            achieve: 10
          }, {
            score: 78,
            achieve: 10.2
          }, {
            score: 76,
            achieve: 10.4
          }, {
            score: 74,
            achieve: 10.6
          }, {
            score: 72,
            achieve: 10.8
          }, {
            score: 70,
            achieve: 11
          }, {
            score: 68,
            achieve: 11.2
          }, {
            score: 66,
            achieve: 11.4
          }, {
            score: 64,
            achieve: 11.6
          }, {
            score: 62,
            achieve: 11.8
          }, {
            score: 60,
            achieve: 12
          }, {
            score: 50,
            achieve: 12.2
          }, {
            score: 40,
            achieve: 12.4
          }, {
            score: 30,
            achieve: 12.6
          }, {
            score: 20,
            achieve: 12.8
          }, {
            score: 10,
            achieve: 13
          }]
        }, {
          name: "坐位体前屈",
          unit: "厘米",
          weighting: .3,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 16.2
          }, {
            score: 95,
            achieve: 14.7
          }, {
            score: 90,
            achieve: 13.2
          }, {
            score: 85,
            achieve: 11.9
          }, {
            score: 80,
            achieve: 10.6
          }, {
            score: 78,
            achieve: 9.5
          }, {
            score: 76,
            achieve: 8.4
          }, {
            score: 74,
            achieve: 7.3
          }, {
            score: 72,
            achieve: 6.2
          }, {
            score: 70,
            achieve: 5.1
          }, {
            score: 68,
            achieve: 4
          }, {
            score: 66,
            achieve: 2.9
          }, {
            score: 64,
            achieve: 1.8
          }, {
            score: 62,
            achieve: .7
          }, {
            score: 60,
            achieve: -.4
          }, {
            score: 50,
            achieve: -1.2
          }, {
            score: 40,
            achieve: -2
          }, {
            score: 30,
            achieve: -2.8
          }, {
            score: 20,
            achieve: -3.6
          }, {
            score: 10,
            achieve: -4.4
          }]
        }, {
          name: "一分钟跳绳",
          unit: "个",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 117
          }, {
            score: 95,
            achieve: 112
          }, {
            score: 90,
            achieve: 107
          }, {
            score: 85,
            achieve: 101
          }, {
            score: 80,
            achieve: 95
          }, {
            score: 78,
            achieve: 88
          }, {
            score: 76,
            achieve: 81
          }, {
            score: 74,
            achieve: 74
          }, {
            score: 72,
            achieve: 67
          }, {
            score: 70,
            achieve: 60
          }, {
            score: 68,
            achieve: 53
          }, {
            score: 66,
            achieve: 46
          }, {
            score: 64,
            achieve: 39
          }, {
            score: 62,
            achieve: 32
          }, {
            score: 60,
            achieve: 25
          }, {
            score: 50,
            achieve: 22
          }, {
            score: 40,
            achieve: 19
          }, {
            score: 30,
            achieve: 16
          }, {
            score: 20,
            achieve: 13
          }, {
            score: 10,
            achieve: 10
          }]
        }]), "二年级" == e && "女生" == c && (this.sports = [{
          name: "肺活量",
          unit: "毫升",
          weighting: .15,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 1600
          }, {
            score: 95,
            achieve: 1500
          }, {
            score: 90,
            achieve: 1400
          }, {
            score: 85,
            achieve: 1300
          }, {
            score: 80,
            achieve: 1200
          }, {
            score: 78,
            achieve: 1150
          }, {
            score: 76,
            achieve: 1100
          }, {
            score: 74,
            achieve: 1050
          }, {
            score: 72,
            achieve: 1e3
          }, {
            score: 70,
            achieve: 950
          }, {
            score: 68,
            achieve: 900
          }, {
            score: 66,
            achieve: 850
          }, {
            score: 64,
            achieve: 800
          }, {
            score: 62,
            achieve: 750
          }, {
            score: 60,
            achieve: 700
          }, {
            score: 50,
            achieve: 680
          }, {
            score: 40,
            achieve: 660
          }, {
            score: 30,
            achieve: 640
          }, {
            score: 20,
            achieve: 620
          }, {
            score: 10,
            achieve: 600
          }]
        }, {
          name: "50米跑",
          unit: "秒",
          weighting: .2,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 10
          }, {
            score: 95,
            achieve: 10.1
          }, {
            score: 90,
            achieve: 10.2
          }, {
            score: 85,
            achieve: 10.5
          }, {
            score: 80,
            achieve: 10.8
          }, {
            score: 78,
            achieve: 11
          }, {
            score: 76,
            achieve: 11.2
          }, {
            score: 74,
            achieve: 11.4
          }, {
            score: 72,
            achieve: 11.6
          }, {
            score: 70,
            achieve: 11.8
          }, {
            score: 68,
            achieve: 12
          }, {
            score: 66,
            achieve: 12.2
          }, {
            score: 64,
            achieve: 12.4
          }, {
            score: 62,
            achieve: 12.6
          }, {
            score: 60,
            achieve: 12.8
          }, {
            score: 50,
            achieve: 13
          }, {
            score: 40,
            achieve: 13.2
          }, {
            score: 30,
            achieve: 13.4
          }, {
            score: 20,
            achieve: 13.6
          }, {
            score: 10,
            achieve: 13.8
          }]
        }, {
          name: "坐位体前屈",
          unit: "厘米",
          weighting: .3,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 18.9
          }, {
            score: 95,
            achieve: 17.6
          }, {
            score: 90,
            achieve: 16.3
          }, {
            score: 85,
            achieve: 14.8
          }, {
            score: 80,
            achieve: 13.3
          }, {
            score: 78,
            achieve: 12.2
          }, {
            score: 76,
            achieve: 11.1
          }, {
            score: 74,
            achieve: 10
          }, {
            score: 72,
            achieve: 8.9
          }, {
            score: 70,
            achieve: 7.8
          }, {
            score: 68,
            achieve: 6.7
          }, {
            score: 66,
            achieve: 5.6
          }, {
            score: 64,
            achieve: 4.5
          }, {
            score: 62,
            achieve: 3.4
          }, {
            score: 60,
            achieve: 2.3
          }, {
            score: 50,
            achieve: 1.5
          }, {
            score: 40,
            achieve: .7
          }, {
            score: 30,
            achieve: -.1
          }, {
            score: 20,
            achieve: -.9
          }, {
            score: 10,
            achieve: -1.7
          }]
        }, {
          name: "一分钟跳绳",
          unit: "个",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 127
          }, {
            score: 95,
            achieve: 120
          }, {
            score: 90,
            achieve: 113
          }, {
            score: 85,
            achieve: 105
          }, {
            score: 80,
            achieve: 97
          }, {
            score: 78,
            achieve: 90
          }, {
            score: 76,
            achieve: 83
          }, {
            score: 74,
            achieve: 76
          }, {
            score: 72,
            achieve: 69
          }, {
            score: 70,
            achieve: 62
          }, {
            score: 68,
            achieve: 55
          }, {
            score: 66,
            achieve: 48
          }, {
            score: 64,
            achieve: 41
          }, {
            score: 62,
            achieve: 34
          }, {
            score: 60,
            achieve: 27
          }, {
            score: 50,
            achieve: 24
          }, {
            score: 40,
            achieve: 21
          }, {
            score: 30,
            achieve: 18
          }, {
            score: 20,
            achieve: 15
          }, {
            score: 10,
            achieve: 12
          }]
        }]), "三年级" == e && "男生" == c && (this.sports = [{
          name: "肺活量",
          unit: "毫升",
          weighting: .15,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 2300
          }, {
            score: 95,
            achieve: 2200
          }, {
            score: 90,
            achieve: 2100
          }, {
            score: 85,
            achieve: 1900
          }, {
            score: 80,
            achieve: 1700
          }, {
            score: 78,
            achieve: 1620
          }, {
            score: 76,
            achieve: 1540
          }, {
            score: 74,
            achieve: 1460
          }, {
            score: 72,
            achieve: 1380
          }, {
            score: 70,
            achieve: 1300
          }, {
            score: 68,
            achieve: 1220
          }, {
            score: 66,
            achieve: 1140
          }, {
            score: 64,
            achieve: 1060
          }, {
            score: 62,
            achieve: 980
          }, {
            score: 60,
            achieve: 900
          }, {
            score: 50,
            achieve: 840
          }, {
            score: 40,
            achieve: 780
          }, {
            score: 30,
            achieve: 720
          }, {
            score: 20,
            achieve: 660
          }, {
            score: 10,
            achieve: 600
          }]
        }, {
          name: "50米跑",
          unit: "秒",
          weighting: .2,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 9.1
          }, {
            score: 95,
            achieve: 9.2
          }, {
            score: 90,
            achieve: 9.3
          }, {
            score: 85,
            achieve: 9.4
          }, {
            score: 80,
            achieve: 9.5
          }, {
            score: 78,
            achieve: 9.7
          }, {
            score: 76,
            achieve: 9.9
          }, {
            score: 74,
            achieve: 10.1
          }, {
            score: 72,
            achieve: 10.3
          }, {
            score: 70,
            achieve: 10.5
          }, {
            score: 68,
            achieve: 10.7
          }, {
            score: 66,
            achieve: 10.9
          }, {
            score: 64,
            achieve: 11.1
          }, {
            score: 62,
            achieve: 11.3
          }, {
            score: 60,
            achieve: 11.5
          }, {
            score: 50,
            achieve: 11.7
          }, {
            score: 40,
            achieve: 11.9
          }, {
            score: 30,
            achieve: 12.1
          }, {
            score: 20,
            achieve: 12.3
          }, {
            score: 10,
            achieve: 12.5
          }]
        }, {
          name: "坐位体前屈",
          unit: "厘米",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 16.3
          }, {
            score: 95,
            achieve: 14.9
          }, {
            score: 90,
            achieve: 13.4
          }, {
            score: 85,
            achieve: 11.8
          }, {
            score: 80,
            achieve: 10.2
          }, {
            score: 78,
            achieve: 9.1
          }, {
            score: 76,
            achieve: 8
          }, {
            score: 74,
            achieve: 6.9
          }, {
            score: 72,
            achieve: 5.8
          }, {
            score: 70,
            achieve: 4.7
          }, {
            score: 68,
            achieve: 3.6
          }, {
            score: 66,
            achieve: 2.5
          }, {
            score: 64,
            achieve: 1.4
          }, {
            score: 62,
            achieve: .3
          }, {
            score: 60,
            achieve: -.8
          }, {
            score: 50,
            achieve: -1.6
          }, {
            score: 40,
            achieve: -2.4
          }, {
            score: 30,
            achieve: -3.2
          }, {
            score: 20,
            achieve: -4
          }, {
            score: 10,
            achieve: -4.8
          }]
        }, {
          name: "一分钟跳绳",
          unit: "个",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 126
          }, {
            score: 95,
            achieve: 121
          }, {
            score: 90,
            achieve: 116
          }, {
            score: 85,
            achieve: 110
          }, {
            score: 80,
            achieve: 104
          }, {
            score: 78,
            achieve: 97
          }, {
            score: 76,
            achieve: 90
          }, {
            score: 74,
            achieve: 83
          }, {
            score: 72,
            achieve: 76
          }, {
            score: 70,
            achieve: 69
          }, {
            score: 68,
            achieve: 62
          }, {
            score: 66,
            achieve: 55
          }, {
            score: 64,
            achieve: 48
          }, {
            score: 62,
            achieve: 41
          }, {
            score: 60,
            achieve: 34
          }, {
            score: 50,
            achieve: 31
          }, {
            score: 40,
            achieve: 28
          }, {
            score: 30,
            achieve: 25
          }, {
            score: 20,
            achieve: 22
          }, {
            score: 10,
            achieve: 19
          }]
        }, {
          name: "一分钟仰卧起坐",
          unit: "个",
          weighting: .1,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 48
          }, {
            score: 95,
            achieve: 45
          }, {
            score: 90,
            achieve: 42
          }, {
            score: 85,
            achieve: 39
          }, {
            score: 80,
            achieve: 36
          }, {
            score: 78,
            achieve: 34
          }, {
            score: 76,
            achieve: 32
          }, {
            score: 74,
            achieve: 30
          }, {
            score: 72,
            achieve: 28
          }, {
            score: 70,
            achieve: 26
          }, {
            score: 68,
            achieve: 24
          }, {
            score: 66,
            achieve: 22
          }, {
            score: 64,
            achieve: 20
          }, {
            score: 62,
            achieve: 18
          }, {
            score: 60,
            achieve: 16
          }, {
            score: 50,
            achieve: 14
          }, {
            score: 40,
            achieve: 12
          }, {
            score: 30,
            achieve: 10
          }, {
            score: 20,
            achieve: 8
          }, {
            score: 10,
            achieve: 6
          }]
        }]), "三年级" == e && "女生" == c && (this.sports = [{
          name: "肺活量",
          unit: "毫升",
          weighting: .15,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 1800
          }, {
            score: 95,
            achieve: 1700
          }, {
            score: 90,
            achieve: 1600
          }, {
            score: 85,
            achieve: 1500
          }, {
            score: 80,
            achieve: 1400
          }, {
            score: 78,
            achieve: 1340
          }, {
            score: 76,
            achieve: 1280
          }, {
            score: 74,
            achieve: 1220
          }, {
            score: 72,
            achieve: 1160
          }, {
            score: 70,
            achieve: 1100
          }, {
            score: 68,
            achieve: 1040
          }, {
            score: 66,
            achieve: 980
          }, {
            score: 64,
            achieve: 920
          }, {
            score: 62,
            achieve: 860
          }, {
            score: 60,
            achieve: 800
          }, {
            score: 50,
            achieve: 780
          }, {
            score: 40,
            achieve: 760
          }, {
            score: 30,
            achieve: 740
          }, {
            score: 20,
            achieve: 720
          }, {
            score: 10,
            achieve: 700
          }]
        }, {
          name: "50米跑",
          unit: "秒",
          weighting: .2,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 9.2
          }, {
            score: 95,
            achieve: 9.3
          }, {
            score: 90,
            achieve: 9.4
          }, {
            score: 85,
            achieve: 9.7
          }, {
            score: 80,
            achieve: 10
          }, {
            score: 78,
            achieve: 10.2
          }, {
            score: 76,
            achieve: 10.4
          }, {
            score: 74,
            achieve: 10.6
          }, {
            score: 72,
            achieve: 10.8
          }, {
            score: 70,
            achieve: 11
          }, {
            score: 68,
            achieve: 11.2
          }, {
            score: 66,
            achieve: 11.4
          }, {
            score: 64,
            achieve: 11.6
          }, {
            score: 62,
            achieve: 11.8
          }, {
            score: 60,
            achieve: 12
          }, {
            score: 50,
            achieve: 12.2
          }, {
            score: 40,
            achieve: 12.4
          }, {
            score: 30,
            achieve: 12.6
          }, {
            score: 20,
            achieve: 12.8
          }, {
            score: 10,
            achieve: 13
          }]
        }, {
          name: "坐位体前屈",
          unit: "厘米",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 19.2
          }, {
            score: 95,
            achieve: 17.9
          }, {
            score: 90,
            achieve: 16.6
          }, {
            score: 85,
            achieve: 14.9
          }, {
            score: 80,
            achieve: 13.2
          }, {
            score: 78,
            achieve: 12.1
          }, {
            score: 76,
            achieve: 11
          }, {
            score: 74,
            achieve: 9.9
          }, {
            score: 72,
            achieve: 8.8
          }, {
            score: 70,
            achieve: 7.7
          }, {
            score: 68,
            achieve: 6.6
          }, {
            score: 66,
            achieve: 5.5
          }, {
            score: 64,
            achieve: 4.4
          }, {
            score: 62,
            achieve: 3.3
          }, {
            score: 60,
            achieve: 2.2
          }, {
            score: 50,
            achieve: 1.4
          }, {
            score: 40,
            achieve: .6
          }, {
            score: 30,
            achieve: -.2
          }, {
            score: 20,
            achieve: -1
          }, {
            score: 10,
            achieve: -1.8
          }]
        }, {
          name: "一分钟跳绳",
          unit: "个",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 139
          }, {
            score: 95,
            achieve: 132
          }, {
            score: 90,
            achieve: 125
          }, {
            score: 85,
            achieve: 117
          }, {
            score: 80,
            achieve: 109
          }, {
            score: 78,
            achieve: 102
          }, {
            score: 76,
            achieve: 95
          }, {
            score: 74,
            achieve: 88
          }, {
            score: 72,
            achieve: 81
          }, {
            score: 70,
            achieve: 74
          }, {
            score: 68,
            achieve: 67
          }, {
            score: 66,
            achieve: 60
          }, {
            score: 64,
            achieve: 53
          }, {
            score: 62,
            achieve: 46
          }, {
            score: 60,
            achieve: 39
          }, {
            score: 50,
            achieve: 36
          }, {
            score: 40,
            achieve: 33
          }, {
            score: 30,
            achieve: 30
          }, {
            score: 20,
            achieve: 27
          }, {
            score: 10,
            achieve: 24
          }]
        }, {
          name: "一分钟仰卧起坐",
          unit: "个",
          weighting: .1,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 46
          }, {
            score: 95,
            achieve: 44
          }, {
            score: 90,
            achieve: 42
          }, {
            score: 85,
            achieve: 39
          }, {
            score: 80,
            achieve: 36
          }, {
            score: 78,
            achieve: 34
          }, {
            score: 76,
            achieve: 32
          }, {
            score: 74,
            achieve: 30
          }, {
            score: 72,
            achieve: 28
          }, {
            score: 70,
            achieve: 26
          }, {
            score: 68,
            achieve: 24
          }, {
            score: 66,
            achieve: 22
          }, {
            score: 64,
            achieve: 20
          }, {
            score: 62,
            achieve: 18
          }, {
            score: 60,
            achieve: 16
          }, {
            score: 50,
            achieve: 14
          }, {
            score: 40,
            achieve: 12
          }, {
            score: 30,
            achieve: 10
          }, {
            score: 20,
            achieve: 8
          }, {
            score: 10,
            achieve: 6
          }]
        }]), "四年级" == e && "男生" == c && (this.sports = [{
          name: "肺活量",
          unit: "毫升",
          weighting: .15,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 2600
          }, {
            score: 95,
            achieve: 2500
          }, {
            score: 90,
            achieve: 2400
          }, {
            score: 85,
            achieve: 2150
          }, {
            score: 80,
            achieve: 1900
          }, {
            score: 78,
            achieve: 1820
          }, {
            score: 76,
            achieve: 1740
          }, {
            score: 74,
            achieve: 1660
          }, {
            score: 72,
            achieve: 1580
          }, {
            score: 70,
            achieve: 1500
          }, {
            score: 68,
            achieve: 1420
          }, {
            score: 66,
            achieve: 1340
          }, {
            score: 64,
            achieve: 1260
          }, {
            score: 62,
            achieve: 1180
          }, {
            score: 60,
            achieve: 1100
          }, {
            score: 50,
            achieve: 1030
          }, {
            score: 40,
            achieve: 960
          }, {
            score: 30,
            achieve: 890
          }, {
            score: 20,
            achieve: 820
          }, {
            score: 10,
            achieve: 750
          }]
        }, {
          name: "50米跑",
          unit: "秒",
          weighting: .2,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 8.7
          }, {
            score: 95,
            achieve: 8.8
          }, {
            score: 90,
            achieve: 8.9
          }, {
            score: 85,
            achieve: 9
          }, {
            score: 80,
            achieve: 9.1
          }, {
            score: 78,
            achieve: 9.3
          }, {
            score: 76,
            achieve: 9.5
          }, {
            score: 74,
            achieve: 9.7
          }, {
            score: 72,
            achieve: 9.9
          }, {
            score: 70,
            achieve: 10.1
          }, {
            score: 68,
            achieve: 10.3
          }, {
            score: 66,
            achieve: 10.5
          }, {
            score: 64,
            achieve: 10.7
          }, {
            score: 62,
            achieve: 10.9
          }, {
            score: 60,
            achieve: 11.1
          }, {
            score: 50,
            achieve: 11.3
          }, {
            score: 40,
            achieve: 11.5
          }, {
            score: 30,
            achieve: 11.7
          }, {
            score: 20,
            achieve: 11.9
          }, {
            score: 10,
            achieve: 12.1
          }]
        }, {
          name: "坐位体前屈",
          unit: "厘米",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 16.4
          }, {
            score: 95,
            achieve: 15
          }, {
            score: 90,
            achieve: 13.6
          }, {
            score: 85,
            achieve: 11.7
          }, {
            score: 80,
            achieve: 9.8
          }, {
            score: 78,
            achieve: 8.6
          }, {
            score: 76,
            achieve: 7.4
          }, {
            score: 74,
            achieve: 6.2
          }, {
            score: 72,
            achieve: 5
          }, {
            score: 70,
            achieve: 3.8
          }, {
            score: 68,
            achieve: 2.6
          }, {
            score: 66,
            achieve: 1.4
          }, {
            score: 64,
            achieve: .2
          }, {
            score: 62,
            achieve: -1
          }, {
            score: 60,
            achieve: -2.2
          }, {
            score: 50,
            achieve: -3.2
          }, {
            score: 40,
            achieve: -4.2
          }, {
            score: 30,
            achieve: -5.2
          }, {
            score: 20,
            achieve: -6.2
          }, {
            score: 10,
            achieve: -7.2
          }]
        }, {
          name: "一分钟跳绳",
          unit: "个",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 137
          }, {
            score: 95,
            achieve: 132
          }, {
            score: 90,
            achieve: 127
          }, {
            score: 85,
            achieve: 121
          }, {
            score: 80,
            achieve: 115
          }, {
            score: 78,
            achieve: 108
          }, {
            score: 76,
            achieve: 101
          }, {
            score: 74,
            achieve: 94
          }, {
            score: 72,
            achieve: 87
          }, {
            score: 70,
            achieve: 80
          }, {
            score: 68,
            achieve: 73
          }, {
            score: 66,
            achieve: 66
          }, {
            score: 64,
            achieve: 59
          }, {
            score: 62,
            achieve: 52
          }, {
            score: 60,
            achieve: 45
          }, {
            score: 50,
            achieve: 42
          }, {
            score: 40,
            achieve: 39
          }, {
            score: 30,
            achieve: 36
          }, {
            score: 20,
            achieve: 33
          }, {
            score: 10,
            achieve: 30
          }]
        }, {
          name: "一分钟仰卧起坐",
          unit: "个",
          weighting: .1,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 49
          }, {
            score: 95,
            achieve: 46
          }, {
            score: 90,
            achieve: 43
          }, {
            score: 85,
            achieve: 40
          }, {
            score: 80,
            achieve: 37
          }, {
            score: 78,
            achieve: 35
          }, {
            score: 76,
            achieve: 33
          }, {
            score: 74,
            achieve: 31
          }, {
            score: 72,
            achieve: 29
          }, {
            score: 70,
            achieve: 27
          }, {
            score: 68,
            achieve: 25
          }, {
            score: 66,
            achieve: 23
          }, {
            score: 64,
            achieve: 21
          }, {
            score: 62,
            achieve: 19
          }, {
            score: 60,
            achieve: 17
          }, {
            score: 50,
            achieve: 15
          }, {
            score: 40,
            achieve: 13
          }, {
            score: 30,
            achieve: 11
          }, {
            score: 20,
            achieve: 9
          }, {
            score: 10,
            achieve: 7
          }]
        }]), "四年级" == e && "女生" == c && (this.sports = [{
          name: "肺活量",
          unit: "毫升",
          weighting: .15,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 2e3
          }, {
            score: 95,
            achieve: 1900
          }, {
            score: 90,
            achieve: 1800
          }, {
            score: 85,
            achieve: 1700
          }, {
            score: 80,
            achieve: 1600
          }, {
            score: 78,
            achieve: 1530
          }, {
            score: 76,
            achieve: 1460
          }, {
            score: 74,
            achieve: 1390
          }, {
            score: 72,
            achieve: 1320
          }, {
            score: 70,
            achieve: 1250
          }, {
            score: 68,
            achieve: 1180
          }, {
            score: 66,
            achieve: 1110
          }, {
            score: 64,
            achieve: 1040
          }, {
            score: 62,
            achieve: 970
          }, {
            score: 60,
            achieve: 900
          }, {
            score: 50,
            achieve: 880
          }, {
            score: 40,
            achieve: 860
          }, {
            score: 30,
            achieve: 840
          }, {
            score: 20,
            achieve: 820
          }, {
            score: 10,
            achieve: 800
          }]
        }, {
          name: "50米跑",
          unit: "秒",
          weighting: .2,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 8.7
          }, {
            score: 95,
            achieve: 8.8
          }, {
            score: 90,
            achieve: 8.9
          }, {
            score: 85,
            achieve: 9.2
          }, {
            score: 80,
            achieve: 9.5
          }, {
            score: 78,
            achieve: 9.7
          }, {
            score: 76,
            achieve: 9.9
          }, {
            score: 74,
            achieve: 10.1
          }, {
            score: 72,
            achieve: 10.3
          }, {
            score: 70,
            achieve: 10.5
          }, {
            score: 68,
            achieve: 10.7
          }, {
            score: 66,
            achieve: 10.9
          }, {
            score: 64,
            achieve: 11.1
          }, {
            score: 62,
            achieve: 11.3
          }, {
            score: 60,
            achieve: 11.5
          }, {
            score: 50,
            achieve: 11.7
          }, {
            score: 40,
            achieve: 11.9
          }, {
            score: 30,
            achieve: 12.1
          }, {
            score: 20,
            achieve: 12.3
          }, {
            score: 10,
            achieve: 12.5
          }]
        }, {
          name: "坐位体前屈",
          unit: "厘米",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 19.5
          }, {
            score: 95,
            achieve: 18.1
          }, {
            score: 90,
            achieve: 16.9
          }, {
            score: 85,
            achieve: 15
          }, {
            score: 80,
            achieve: 13.1
          }, {
            score: 78,
            achieve: 12
          }, {
            score: 76,
            achieve: 10.9
          }, {
            score: 74,
            achieve: 9.8
          }, {
            score: 72,
            achieve: 8.7
          }, {
            score: 70,
            achieve: 7.6
          }, {
            score: 68,
            achieve: 6.5
          }, {
            score: 66,
            achieve: 5.4
          }, {
            score: 64,
            achieve: 4.3
          }, {
            score: 62,
            achieve: 3.2
          }, {
            score: 60,
            achieve: 2.1
          }, {
            score: 50,
            achieve: 1.3
          }, {
            score: 40,
            achieve: .5
          }, {
            score: 30,
            achieve: -.3
          }, {
            score: 20,
            achieve: -1.1
          }, {
            score: 10,
            achieve: -1.9
          }]
        }, {
          name: "一分钟跳绳",
          unit: "个",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 149
          }, {
            score: 95,
            achieve: 142
          }, {
            score: 90,
            achieve: 135
          }, {
            score: 85,
            achieve: 127
          }, {
            score: 80,
            achieve: 119
          }, {
            score: 78,
            achieve: 112
          }, {
            score: 76,
            achieve: 105
          }, {
            score: 74,
            achieve: 98
          }, {
            score: 72,
            achieve: 91
          }, {
            score: 70,
            achieve: 84
          }, {
            score: 68,
            achieve: 77
          }, {
            score: 66,
            achieve: 70
          }, {
            score: 64,
            achieve: 63
          }, {
            score: 62,
            achieve: 56
          }, {
            score: 60,
            achieve: 49
          }, {
            score: 50,
            achieve: 46
          }, {
            score: 40,
            achieve: 43
          }, {
            score: 30,
            achieve: 40
          }, {
            score: 20,
            achieve: 37
          }, {
            score: 10,
            achieve: 34
          }]
        }, {
          name: "一分钟仰卧起坐",
          unit: "个",
          weighting: .1,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 47
          }, {
            score: 95,
            achieve: 45
          }, {
            score: 90,
            achieve: 43
          }, {
            score: 85,
            achieve: 40
          }, {
            score: 80,
            achieve: 37
          }, {
            score: 78,
            achieve: 35
          }, {
            score: 76,
            achieve: 33
          }, {
            score: 74,
            achieve: 31
          }, {
            score: 72,
            achieve: 29
          }, {
            score: 70,
            achieve: 27
          }, {
            score: 68,
            achieve: 25
          }, {
            score: 66,
            achieve: 23
          }, {
            score: 64,
            achieve: 21
          }, {
            score: 62,
            achieve: 19
          }, {
            score: 60,
            achieve: 17
          }, {
            score: 50,
            achieve: 15
          }, {
            score: 40,
            achieve: 13
          }, {
            score: 30,
            achieve: 11
          }, {
            score: 20,
            achieve: 9
          }, {
            score: 10,
            achieve: 7
          }]
        }]), "五年级" == e && "男生" == c && (this.sports = [{
          name: "肺活量",
          unit: "毫升",
          weighting: .15,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 2900
          }, {
            score: 95,
            achieve: 2800
          }, {
            score: 90,
            achieve: 2700
          }, {
            score: 85,
            achieve: 2450
          }, {
            score: 80,
            achieve: 2200
          }, {
            score: 78,
            achieve: 2110
          }, {
            score: 76,
            achieve: 2020
          }, {
            score: 74,
            achieve: 1930
          }, {
            score: 72,
            achieve: 1840
          }, {
            score: 70,
            achieve: 1750
          }, {
            score: 68,
            achieve: 1660
          }, {
            score: 66,
            achieve: 1570
          }, {
            score: 64,
            achieve: 1480
          }, {
            score: 62,
            achieve: 1390
          }, {
            score: 60,
            achieve: 1300
          }, {
            score: 50,
            achieve: 1220
          }, {
            score: 40,
            achieve: 1140
          }, {
            score: 30,
            achieve: 1060
          }, {
            score: 20,
            achieve: 980
          }, {
            score: 10,
            achieve: 900
          }]
        }, {
          name: "50米跑",
          unit: "秒",
          weighting: .2,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 8.4
          }, {
            score: 95,
            achieve: 8.5
          }, {
            score: 90,
            achieve: 8.6
          }, {
            score: 85,
            achieve: 8.7
          }, {
            score: 80,
            achieve: 8.8
          }, {
            score: 78,
            achieve: 9
          }, {
            score: 76,
            achieve: 9.2
          }, {
            score: 74,
            achieve: 9.4
          }, {
            score: 72,
            achieve: 9.6
          }, {
            score: 70,
            achieve: 9.8
          }, {
            score: 68,
            achieve: 10
          }, {
            score: 66,
            achieve: 10.2
          }, {
            score: 64,
            achieve: 10.4
          }, {
            score: 62,
            achieve: 10.6
          }, {
            score: 60,
            achieve: 10.8
          }, {
            score: 50,
            achieve: 11
          }, {
            score: 40,
            achieve: 11.2
          }, {
            score: 30,
            achieve: 11.4
          }, {
            score: 20,
            achieve: 11.6
          }, {
            score: 10,
            achieve: 11.8
          }]
        }, {
          name: "坐位体前屈",
          unit: "厘米",
          weighting: .1,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 16.5
          }, {
            score: 95,
            achieve: 15.2
          }, {
            score: 90,
            achieve: 13.8
          }, {
            score: 85,
            achieve: 11.6
          }, {
            score: 80,
            achieve: 9.4
          }, {
            score: 78,
            achieve: 8.2
          }, {
            score: 76,
            achieve: 7
          }, {
            score: 74,
            achieve: 5.8
          }, {
            score: 72,
            achieve: 4.6
          }, {
            score: 70,
            achieve: 3.4
          }, {
            score: 68,
            achieve: 2.2
          }, {
            score: 66,
            achieve: 1
          }, {
            score: 64,
            achieve: -.2
          }, {
            score: 62,
            achieve: -1.4
          }, {
            score: 60,
            achieve: -2.6
          }, {
            score: 50,
            achieve: -3.6
          }, {
            score: 40,
            achieve: -4.6
          }, {
            score: 30,
            achieve: -5.6
          }, {
            score: 20,
            achieve: -6.6
          }, {
            score: 10,
            achieve: -7.6
          }]
        }, {
          name: "一分钟跳绳",
          unit: "个",
          weighting: .1,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 148
          }, {
            score: 95,
            achieve: 143
          }, {
            score: 90,
            achieve: 138
          }, {
            score: 85,
            achieve: 132
          }, {
            score: 80,
            achieve: 126
          }, {
            score: 78,
            achieve: 119
          }, {
            score: 76,
            achieve: 112
          }, {
            score: 74,
            achieve: 105
          }, {
            score: 72,
            achieve: 98
          }, {
            score: 70,
            achieve: 91
          }, {
            score: 68,
            achieve: 84
          }, {
            score: 66,
            achieve: 77
          }, {
            score: 64,
            achieve: 70
          }, {
            score: 62,
            achieve: 63
          }, {
            score: 60,
            achieve: 56
          }, {
            score: 50,
            achieve: 53
          }, {
            score: 40,
            achieve: 50
          }, {
            score: 30,
            achieve: 47
          }, {
            score: 20,
            achieve: 44
          }, {
            score: 10,
            achieve: 41
          }]
        }, {
          name: "一分钟仰卧起坐",
          unit: "个",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 50
          }, {
            score: 95,
            achieve: 47
          }, {
            score: 90,
            achieve: 44
          }, {
            score: 85,
            achieve: 41
          }, {
            score: 80,
            achieve: 38
          }, {
            score: 78,
            achieve: 36
          }, {
            score: 76,
            achieve: 34
          }, {
            score: 74,
            achieve: 32
          }, {
            score: 72,
            achieve: 30
          }, {
            score: 70,
            achieve: 28
          }, {
            score: 68,
            achieve: 26
          }, {
            score: 66,
            achieve: 24
          }, {
            score: 64,
            achieve: 22
          }, {
            score: 62,
            achieve: 20
          }, {
            score: 60,
            achieve: 18
          }, {
            score: 50,
            achieve: 16
          }, {
            score: 40,
            achieve: 14
          }, {
            score: 30,
            achieve: 12
          }, {
            score: 20,
            achieve: 10
          }, {
            score: 10,
            achieve: 8
          }]
        }, {
          name: "50*8往返跑",
          unit: "秒",
          weighting: .1,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 96
          }, {
            score: 95,
            achieve: 99
          }, {
            score: 90,
            achieve: 102
          }, {
            score: 85,
            achieve: 105
          }, {
            score: 80,
            achieve: 108
          }, {
            score: 78,
            achieve: 111
          }, {
            score: 76,
            achieve: 114
          }, {
            score: 74,
            achieve: 117
          }, {
            score: 72,
            achieve: 120
          }, {
            score: 70,
            achieve: 123
          }, {
            score: 68,
            achieve: 126
          }, {
            score: 66,
            achieve: 129
          }, {
            score: 64,
            achieve: 132
          }, {
            score: 62,
            achieve: 135
          }, {
            score: 60,
            achieve: 138
          }, {
            score: 50,
            achieve: 142
          }, {
            score: 40,
            achieve: 146
          }, {
            score: 30,
            achieve: 150
          }, {
            score: 20,
            achieve: 154
          }, {
            score: 10,
            achieve: 158
          }]
        }]), "五年级" == e && "女生" == c && (this.sports = [{
          name: "肺活量",
          unit: "毫升",
          weighting: .15,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 2250
          }, {
            score: 95,
            achieve: 2150
          }, {
            score: 90,
            achieve: 2050
          }, {
            score: 85,
            achieve: 1950
          }, {
            score: 80,
            achieve: 1850
          }, {
            score: 78,
            achieve: 1770
          }, {
            score: 76,
            achieve: 1690
          }, {
            score: 74,
            achieve: 1610
          }, {
            score: 72,
            achieve: 1530
          }, {
            score: 70,
            achieve: 1450
          }, {
            score: 68,
            achieve: 1370
          }, {
            score: 66,
            achieve: 1290
          }, {
            score: 64,
            achieve: 1210
          }, {
            score: 62,
            achieve: 1130
          }, {
            score: 60,
            achieve: 1050
          }, {
            score: 50,
            achieve: 1020
          }, {
            score: 40,
            achieve: 990
          }, {
            score: 30,
            achieve: 960
          }, {
            score: 20,
            achieve: 930
          }, {
            score: 10,
            achieve: 900
          }]
        }, {
          name: "50米跑",
          unit: "秒",
          weighting: .2,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 8.3
          }, {
            score: 95,
            achieve: 8.4
          }, {
            score: 90,
            achieve: 8.5
          }, {
            score: 85,
            achieve: 8.8
          }, {
            score: 80,
            achieve: 9.1
          }, {
            score: 78,
            achieve: 9.3
          }, {
            score: 76,
            achieve: 9.5
          }, {
            score: 74,
            achieve: 9.7
          }, {
            score: 72,
            achieve: 9.9
          }, {
            score: 70,
            achieve: 10.1
          }, {
            score: 68,
            achieve: 10.3
          }, {
            score: 66,
            achieve: 10.5
          }, {
            score: 64,
            achieve: 10.7
          }, {
            score: 62,
            achieve: 10.9
          }, {
            score: 60,
            achieve: 11.1
          }, {
            score: 50,
            achieve: 11.3
          }, {
            score: 40,
            achieve: 11.5
          }, {
            score: 30,
            achieve: 11.7
          }, {
            score: 20,
            achieve: 11.9
          }, {
            score: 10,
            achieve: 12.1
          }]
        }, {
          name: "坐位体前屈",
          unit: "厘米",
          weighting: .1,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 19.8
          }, {
            score: 95,
            achieve: 18.5
          }, {
            score: 90,
            achieve: 17.2
          }, {
            score: 85,
            achieve: 15.1
          }, {
            score: 80,
            achieve: 13
          }, {
            score: 78,
            achieve: 11.9
          }, {
            score: 76,
            achieve: 10.8
          }, {
            score: 74,
            achieve: 9.7
          }, {
            score: 72,
            achieve: 8.6
          }, {
            score: 70,
            achieve: 7.5
          }, {
            score: 68,
            achieve: 6.4
          }, {
            score: 66,
            achieve: 5.3
          }, {
            score: 64,
            achieve: 4.2
          }, {
            score: 62,
            achieve: 3.1
          }, {
            score: 60,
            achieve: 2
          }, {
            score: 50,
            achieve: 1.2
          }, {
            score: 40,
            achieve: .4
          }, {
            score: 30,
            achieve: -.4
          }, {
            score: 20,
            achieve: -1.2
          }, {
            score: 10,
            achieve: -2
          }]
        }, {
          name: "一分钟跳绳",
          unit: "个",
          weighting: .1,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 158
          }, {
            score: 95,
            achieve: 151
          }, {
            score: 90,
            achieve: 144
          }, {
            score: 85,
            achieve: 136
          }, {
            score: 80,
            achieve: 128
          }, {
            score: 78,
            achieve: 121
          }, {
            score: 76,
            achieve: 114
          }, {
            score: 74,
            achieve: 107
          }, {
            score: 72,
            achieve: 100
          }, {
            score: 70,
            achieve: 93
          }, {
            score: 68,
            achieve: 86
          }, {
            score: 66,
            achieve: 79
          }, {
            score: 64,
            achieve: 72
          }, {
            score: 62,
            achieve: 65
          }, {
            score: 60,
            achieve: 58
          }, {
            score: 50,
            achieve: 55
          }, {
            score: 40,
            achieve: 52
          }, {
            score: 30,
            achieve: 49
          }, {
            score: 20,
            achieve: 46
          }, {
            score: 10,
            achieve: 43
          }]
        }, {
          name: "一分钟仰卧起坐",
          unit: "个",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 48
          }, {
            score: 95,
            achieve: 46
          }, {
            score: 90,
            achieve: 44
          }, {
            score: 85,
            achieve: 41
          }, {
            score: 80,
            achieve: 38
          }, {
            score: 78,
            achieve: 36
          }, {
            score: 76,
            achieve: 34
          }, {
            score: 74,
            achieve: 32
          }, {
            score: 72,
            achieve: 30
          }, {
            score: 70,
            achieve: 28
          }, {
            score: 68,
            achieve: 26
          }, {
            score: 66,
            achieve: 24
          }, {
            score: 64,
            achieve: 22
          }, {
            score: 62,
            achieve: 20
          }, {
            score: 60,
            achieve: 18
          }, {
            score: 50,
            achieve: 16
          }, {
            score: 40,
            achieve: 14
          }, {
            score: 30,
            achieve: 12
          }, {
            score: 20,
            achieve: 10
          }, {
            score: 10,
            achieve: 8
          }]
        }, {
          name: "50*8往返跑",
          unit: "秒",
          weighting: .1,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 101
          }, {
            score: 95,
            achieve: 104
          }, {
            score: 90,
            achieve: 107
          }, {
            score: 85,
            achieve: 110
          }, {
            score: 80,
            achieve: 113
          }, {
            score: 78,
            achieve: 116
          }, {
            score: 76,
            achieve: 119
          }, {
            score: 74,
            achieve: 122
          }, {
            score: 72,
            achieve: 125
          }, {
            score: 70,
            achieve: 128
          }, {
            score: 68,
            achieve: 131
          }, {
            score: 66,
            achieve: 134
          }, {
            score: 64,
            achieve: 137
          }, {
            score: 62,
            achieve: 140
          }, {
            score: 60,
            achieve: 143
          }, {
            score: 50,
            achieve: 147
          }, {
            score: 40,
            achieve: 151
          }, {
            score: 30,
            achieve: 155
          }, {
            score: 20,
            achieve: 159
          }, {
            score: 10,
            achieve: 163
          }]
        }]), "六年级" == e && "男生" == c && (this.sports = [{
          name: "肺活量",
          unit: "毫升",
          weighting: .15,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 3200
          }, {
            score: 95,
            achieve: 3100
          }, {
            score: 90,
            achieve: 3e3
          }, {
            score: 85,
            achieve: 2750
          }, {
            score: 80,
            achieve: 2500
          }, {
            score: 78,
            achieve: 2400
          }, {
            score: 76,
            achieve: 2300
          }, {
            score: 74,
            achieve: 2200
          }, {
            score: 72,
            achieve: 2100
          }, {
            score: 70,
            achieve: 2e3
          }, {
            score: 68,
            achieve: 1900
          }, {
            score: 66,
            achieve: 1800
          }, {
            score: 64,
            achieve: 1700
          }, {
            score: 62,
            achieve: 1600
          }, {
            score: 60,
            achieve: 1500
          }, {
            score: 50,
            achieve: 1410
          }, {
            score: 40,
            achieve: 1320
          }, {
            score: 30,
            achieve: 1230
          }, {
            score: 20,
            achieve: 1140
          }, {
            score: 10,
            achieve: 1050
          }]
        }, {
          name: "50米跑",
          unit: "秒",
          weighting: .2,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 8.2
          }, {
            score: 95,
            achieve: 8.3
          }, {
            score: 90,
            achieve: 8.4
          }, {
            score: 85,
            achieve: 8.5
          }, {
            score: 80,
            achieve: 8.6
          }, {
            score: 78,
            achieve: 8.8
          }, {
            score: 76,
            achieve: 9
          }, {
            score: 74,
            achieve: 9.2
          }, {
            score: 72,
            achieve: 9.4
          }, {
            score: 70,
            achieve: 9.6
          }, {
            score: 68,
            achieve: 9.8
          }, {
            score: 66,
            achieve: 10
          }, {
            score: 64,
            achieve: 10.2
          }, {
            score: 62,
            achieve: 10.4
          }, {
            score: 60,
            achieve: 10.6
          }, {
            score: 50,
            achieve: 10.8
          }, {
            score: 40,
            achieve: 11
          }, {
            score: 30,
            achieve: 11.2
          }, {
            score: 20,
            achieve: 11.4
          }, {
            score: 10,
            achieve: 11.6
          }]
        }, {
          name: "坐位体前屈",
          unit: "厘米",
          weighting: .1,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 16.6
          }, {
            score: 95,
            achieve: 15.3
          }, {
            score: 90,
            achieve: 14
          }, {
            score: 85,
            achieve: 11.5
          }, {
            score: 80,
            achieve: 9
          }, {
            score: 78,
            achieve: 7.7
          }, {
            score: 76,
            achieve: 6.4
          }, {
            score: 74,
            achieve: 5.1
          }, {
            score: 72,
            achieve: 3.8
          }, {
            score: 70,
            achieve: 2.5
          }, {
            score: 68,
            achieve: 1.2
          }, {
            score: 66,
            achieve: -.1
          }, {
            score: 64,
            achieve: -1.4
          }, {
            score: 62,
            achieve: -2.7
          }, {
            score: 60,
            achieve: -4
          }, {
            score: 50,
            achieve: -5
          }, {
            score: 40,
            achieve: -6
          }, {
            score: 30,
            achieve: -7
          }, {
            score: 20,
            achieve: -8
          }, {
            score: 10,
            achieve: -9
          }]
        }, {
          name: "一分钟跳绳",
          unit: "个",
          weighting: .1,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 157
          }, {
            score: 95,
            achieve: 152
          }, {
            score: 90,
            achieve: 147
          }, {
            score: 85,
            achieve: 141
          }, {
            score: 80,
            achieve: 135
          }, {
            score: 78,
            achieve: 128
          }, {
            score: 76,
            achieve: 121
          }, {
            score: 74,
            achieve: 114
          }, {
            score: 72,
            achieve: 107
          }, {
            score: 70,
            achieve: 100
          }, {
            score: 68,
            achieve: 93
          }, {
            score: 66,
            achieve: 86
          }, {
            score: 64,
            achieve: 79
          }, {
            score: 62,
            achieve: 72
          }, {
            score: 60,
            achieve: 65
          }, {
            score: 50,
            achieve: 62
          }, {
            score: 40,
            achieve: 59
          }, {
            score: 30,
            achieve: 56
          }, {
            score: 20,
            achieve: 53
          }, {
            score: 10,
            achieve: 50
          }]
        }, {
          name: "一分钟仰卧起坐",
          unit: "个",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 51
          }, {
            score: 95,
            achieve: 48
          }, {
            score: 90,
            achieve: 45
          }, {
            score: 85,
            achieve: 42
          }, {
            score: 80,
            achieve: 39
          }, {
            score: 78,
            achieve: 37
          }, {
            score: 76,
            achieve: 35
          }, {
            score: 74,
            achieve: 33
          }, {
            score: 72,
            achieve: 31
          }, {
            score: 70,
            achieve: 29
          }, {
            score: 68,
            achieve: 27
          }, {
            score: 66,
            achieve: 25
          }, {
            score: 64,
            achieve: 23
          }, {
            score: 62,
            achieve: 21
          }, {
            score: 60,
            achieve: 19
          }, {
            score: 50,
            achieve: 17
          }, {
            score: 40,
            achieve: 15
          }, {
            score: 30,
            achieve: 13
          }, {
            score: 20,
            achieve: 11
          }, {
            score: 10,
            achieve: 9
          }]
        }, {
          name: "50*8往返跑",
          unit: "秒",
          weighting: .1,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 90
          }, {
            score: 95,
            achieve: 93
          }, {
            score: 90,
            achieve: 96
          }, {
            score: 85,
            achieve: 99
          }, {
            score: 80,
            achieve: 102
          }, {
            score: 78,
            achieve: 105
          }, {
            score: 76,
            achieve: 108
          }, {
            score: 74,
            achieve: 111
          }, {
            score: 72,
            achieve: 114
          }, {
            score: 70,
            achieve: 117
          }, {
            score: 68,
            achieve: 120
          }, {
            score: 66,
            achieve: 123
          }, {
            score: 64,
            achieve: 126
          }, {
            score: 62,
            achieve: 129
          }, {
            score: 60,
            achieve: 132
          }, {
            score: 50,
            achieve: 136
          }, {
            score: 40,
            achieve: 140
          }, {
            score: 30,
            achieve: 144
          }, {
            score: 20,
            achieve: 148
          }, {
            score: 10,
            achieve: 152
          }]
        }]), "六年级" == e && "女生" == c && (this.sports = [{
          name: "肺活量",
          unit: "毫升",
          weighting: .15,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 2500
          }, {
            score: 95,
            achieve: 2400
          }, {
            score: 90,
            achieve: 2300
          }, {
            score: 85,
            achieve: 2200
          }, {
            score: 80,
            achieve: 2100
          }, {
            score: 78,
            achieve: 2010
          }, {
            score: 76,
            achieve: 1920
          }, {
            score: 74,
            achieve: 1830
          }, {
            score: 72,
            achieve: 1740
          }, {
            score: 70,
            achieve: 1650
          }, {
            score: 68,
            achieve: 1560
          }, {
            score: 66,
            achieve: 1470
          }, {
            score: 64,
            achieve: 1380
          }, {
            score: 62,
            achieve: 1290
          }, {
            score: 60,
            achieve: 1200
          }, {
            score: 50,
            achieve: 1170
          }, {
            score: 40,
            achieve: 1140
          }, {
            score: 30,
            achieve: 1110
          }, {
            score: 20,
            achieve: 1080
          }, {
            score: 10,
            achieve: 1050
          }]
        }, {
          name: "50米跑",
          unit: "秒",
          weighting: .2,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 8.2
          }, {
            score: 95,
            achieve: 8.3
          }, {
            score: 90,
            achieve: 8.4
          }, {
            score: 85,
            achieve: 8.7
          }, {
            score: 80,
            achieve: 9
          }, {
            score: 78,
            achieve: 9.2
          }, {
            score: 76,
            achieve: 9.4
          }, {
            score: 74,
            achieve: 9.6
          }, {
            score: 72,
            achieve: 9.8
          }, {
            score: 70,
            achieve: 10
          }, {
            score: 68,
            achieve: 10.2
          }, {
            score: 66,
            achieve: 10.4
          }, {
            score: 64,
            achieve: 10.6
          }, {
            score: 62,
            achieve: 10.8
          }, {
            score: 60,
            achieve: 11
          }, {
            score: 50,
            achieve: 11.2
          }, {
            score: 40,
            achieve: 11.4
          }, {
            score: 30,
            achieve: 11.6
          }, {
            score: 20,
            achieve: 11.8
          }, {
            score: 10,
            achieve: 12
          }]
        }, {
          name: "坐位体前屈",
          unit: "厘米",
          weighting: .1,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 19.9
          }, {
            score: 95,
            achieve: 18.7
          }, {
            score: 90,
            achieve: 17.5
          }, {
            score: 85,
            achieve: 15.2
          }, {
            score: 80,
            achieve: 12.9
          }, {
            score: 78,
            achieve: 11.8
          }, {
            score: 76,
            achieve: 10.7
          }, {
            score: 74,
            achieve: 9.6
          }, {
            score: 72,
            achieve: 8.5
          }, {
            score: 70,
            achieve: 7.4
          }, {
            score: 68,
            achieve: 6.3
          }, {
            score: 66,
            achieve: 5.2
          }, {
            score: 64,
            achieve: 4.1
          }, {
            score: 62,
            achieve: 3
          }, {
            score: 60,
            achieve: 1.9
          }, {
            score: 50,
            achieve: 1.1
          }, {
            score: 40,
            achieve: .3
          }, {
            score: 30,
            achieve: -.5
          }, {
            score: 20,
            achieve: -1.3
          }, {
            score: 10,
            achieve: -2.1
          }]
        }, {
          name: "一分钟跳绳",
          unit: "个",
          weighting: .1,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 166
          }, {
            score: 95,
            achieve: 159
          }, {
            score: 90,
            achieve: 152
          }, {
            score: 85,
            achieve: 144
          }, {
            score: 80,
            achieve: 136
          }, {
            score: 78,
            achieve: 129
          }, {
            score: 76,
            achieve: 122
          }, {
            score: 74,
            achieve: 115
          }, {
            score: 72,
            achieve: 108
          }, {
            score: 70,
            achieve: 101
          }, {
            score: 68,
            achieve: 94
          }, {
            score: 66,
            achieve: 87
          }, {
            score: 64,
            achieve: 80
          }, {
            score: 62,
            achieve: 73
          }, {
            score: 60,
            achieve: 66
          }, {
            score: 50,
            achieve: 63
          }, {
            score: 40,
            achieve: 60
          }, {
            score: 30,
            achieve: 57
          }, {
            score: 20,
            achieve: 54
          }, {
            score: 10,
            achieve: 51
          }]
        }, {
          name: "一分钟仰卧起坐",
          unit: "个",
          weighting: .2,
          reverse: !1,
          references: [{
            score: 100,
            achieve: 49
          }, {
            score: 95,
            achieve: 47
          }, {
            score: 90,
            achieve: 45
          }, {
            score: 85,
            achieve: 42
          }, {
            score: 80,
            achieve: 39
          }, {
            score: 78,
            achieve: 37
          }, {
            score: 76,
            achieve: 35
          }, {
            score: 74,
            achieve: 33
          }, {
            score: 72,
            achieve: 31
          }, {
            score: 70,
            achieve: 29
          }, {
            score: 68,
            achieve: 27
          }, {
            score: 66,
            achieve: 25
          }, {
            score: 64,
            achieve: 23
          }, {
            score: 62,
            achieve: 21
          }, {
            score: 60,
            achieve: 19
          }, {
            score: 50,
            achieve: 17
          }, {
            score: 40,
            achieve: 15
          }, {
            score: 30,
            achieve: 13
          }, {
            score: 20,
            achieve: 11
          }, {
            score: 10,
            achieve: 9
          }]
        }, {
          name: "50*8往返跑",
          unit: "秒",
          weighting: .1,
          reverse: !0,
          references: [{
            score: 100,
            achieve: 97
          }, {
            score: 95,
            achieve: 100
          }, {
            score: 90,
            achieve: 103
          }, {
            score: 85,
            achieve: 106
          }, {
            score: 80,
            achieve: 109
          }, {
            score: 78,
            achieve: 112
          }, {
            score: 76,
            achieve: 115
          }, {
            score: 74,
            achieve: 118
          }, {
            score: 72,
            achieve: 121
          }, {
            score: 70,
            achieve: 124
          }, {
            score: 68,
            achieve: 127
          }, {
            score: 66,
            achieve: 130
          }, {
            score: 64,
            achieve: 133
          }, {
            score: 62,
            achieve: 136
          }, {
            score: 60,
            achieve: 139
          }, {
            score: 50,
            achieve: 143
          }, {
            score: 40,
            achieve: 147
          }, {
            score: 30,
            achieve: 151
          }, {
            score: 20,
            achieve: 155
          }, {
            score: 10,
            achieve: 159
          }]
        }]);
      }
    }
  };if (!Array) {
  (e.resolveComponent("iconfont") + e.resolveComponent("bmi-evaluate") + e.resolveComponent("sport-evaluate") + e.resolveComponent("tui-button") + e.resolveComponent("tui-drawer"))();
}Math || (function () {
  return "../../node-modules/yunzhi.uni-app/components/iconfont.js";
} + function () {
  return "../../components/bmi-evaluate.js";
} + function () {
  return "../../components/sport-evaluate.js";
} + function () {
  return "../../node-modules/yunzhi.uni-app/thorui/tui-button/tui-button.js";
} + function () {
  return "../../node-modules/yunzhi.uni-app/thorui/tui-drawer/tui-drawer.js";
})();var r = e._export_sfc(c, [["render", function (c, r, i, s, o, h) {
  return e.e({
    a: o.currentGrade
  }, o.currentGrade ? {
    b: e.t(o.currentGrade),
    c: e.t(o.currentGender),
    d: e.p({
      size: "22rpx",
      name: "arrow-right"
    })
  } : {
    e: e.p({
      size: "22rpx",
      name: "arrow-right"
    })
  }, {
    f: e.o(function () {
      return h.onPopupGrade && h.onPopupGrade.apply(h, arguments);
    }),
    g: e.t(o.currentGrade),
    h: o.sports
  }, o.sports ? {
    i: e.t(o.sports.length + 1)
  } : {}, {
    j: e.t(o.totalScore.toFixed(1)),
    k: e.o(h.setBmiScore),
    l: e.p({
      grade: o.currentGrade || "一年级",
      gender: o.currentGender || "男生"
    }),
    m: e.f(o.sports, function (c, r, i) {
      return {
        a: e.o(function (e) {
          return h.onHandleResult(r, e);
        }, r),
        b: "a2e706b6-3-" + i,
        c: e.p({
          sport: c
        }),
        d: r
      };
    }),
    n: e.f(o.grades, function (c, r, i) {
      return {
        a: e.t(c),
        b: o.selections[0] == r ? 1 : "",
        c: r
      };
    }),
    o: 0 == o.selections[1] ? 1 : "",
    p: 1 == o.selections[1] ? 1 : "",
    q: o.selections,
    r: e.o(function () {
      return h.onSelectChange && h.onSelectChange.apply(h, arguments);
    }),
    s: e.o(h.onCancel),
    t: e.p({
      type: "gray",
      width: "40vw",
      height: "68rpx",
      shape: "circle",
      shadow: !0
    }),
    v: e.o(h.onConfirm),
    w: e.p({
      type: "primary",
      width: "40vw",
      height: "68rpx",
      shape: "circle",
      shadow: !0
    }),
    x: e.o(h.onPopupGrade),
    y: e.p({
      visible: o.gradeVisibled,
      mode: "bottom"
    })
  });
}]]);wx.createPage(r);